### ISSUE TITLE
Page issue

### ISSUE THREAD

**Issue by Darth-Ness** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#100]
**Describe the bug**
The style Monterrey Fox no page goes to a 404 error page

**To Reproduce**
1. You just click on Monterrey Fox

**Expected behavior**
The page should load

**Desktop (please complete the following information):**
 - OS: [e.g. Linux distro: Garuda Linux (Arch_based)
 - Firefox, Firefox Nightly, Firefox-Developer-Editin, FireDragon (Firefox fork)
 - Version [e.g. 22] 90.0.2

**Comment by Neikon** [comment]
it seems that this repository is now private, I will remove it later.

**Comment by Darth-Ness** [comment]
Okay, thanks for responding so quickly.

**Comment by Neikon** [comment]
The autor will fix it https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/pull/87#issuecomment-898305908

**Comment by AlfarexGuy2019** [comment]
@Darth-Ness I've fixed it 😄

**Comment by Darth-Ness** [comment]
It still goes to 404 for me.

**Comment by AlfarexGuy2019** [comment]
@Darth-Ness Thats because the repository is under maintenance. @Neikon remove it for now, we'll add it later.

**Comment by Neikon** [comment]
ok
