### ISSUE TITLE
[NEWTHEME] MacOSVibrant

### ISSUE THREAD

**Issue by Tnings** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#105]
```
{
		"title": "MacOSVibrant",
		"link": "https://github.com/Tnings/MacosVibrant",
		"description": "A theme that uses MacOS Vibrancy and is styled after other Apple Apps",
		"image": "https://raw.githubusercontent.com/Tnings/MacosVibrant/main/Images/pic_smaller.png"
	}
```

**Comment by Anoms12** [comment]
@Tnings I would like to introduce you to **Sine**, the external mod manager designed for Firefox-based browsers! It offers extensive support for all your Firefox modifications, including `userChrome.css`, `userContent.css`, and user-scripts.

Getting started is simple:

* Add a `theme.json` file to your repository (check out this [reference](https://github.com/Anoms12/Advanced-Tab-Groups/blob/main/theme.json)).

* Then, publish your mod to Sine using [this issue template](https://github.com/CosmoCreeper/Sine/issues/new?template=add-theme.yml).

* If your mod includes configurable options, you can create a `preferences.json` file by [following this wiki](https://github.com/CosmoCreeper/Sine/wiki/Preferences).

The maintainer is very responsive and will review your submission quickly.

Have questions or need assistance? Feel free to tag me!

_Note: Sine currently works with Zen Browser, but version 2, bringing support to all Firefox-based browsers, is just around the corner! Expect the dev branch (Cosine) to be updated with it tonight._
