### ISSUE TITLE
Re-sorting the latest don't show you any change if you don't refresh the website

### ISSUE THREAD

**Issue by Neikon** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#130]
**Describe the bug**
You need to refresh the website to see the changes after re-sorting it by the most recent topics.

**To Reproduce**
1. Click the sort button to switch between sort types.
2. When you switch to random, you instantly see the new sort, and the same with the oldest one. 
3. But when you click to switch back to the "latest" sort, you see no change if you do not refresh the website.

**Expected behavior**
When you come back to "latest" sort, you should see the changes like the others sorting modes

By the way, thank you very much for the new feature 😁

**Comment by BeyondMagic** [comment]
You could've say that on the PR before approving, haha, I put that there exactly for that. I'll fix it soon!

**Comment by BeyondMagic** [comment]
Fixed on 94dab4a.
