### ISSUE TITLE
Opera-GX to Firefox CSS

### ISSUE THREAD

**Issue by Godiesc** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#137]
```
{
		"title": "Opera-GX to Firefox CSS",
		"link": "https://github.com/Godiesc/opera-gx",
		"description": "Firefox Theme CSS to Opera-GX Lovers.",
		"image": "https://user-images.githubusercontent.com/22057609/146305253-e257fbc0-993b-4e79-a0b4-0c0e6c95228b.png"
		"tags": [ "Godiesc", "dark", "opera","gx","theme","adapted","fuchsia","blue" ]
}
```

**Comment by BeyondMagic** [comment]
Add some tags.

```json
{
{
		"title": "Opera-GX to Firefox CSS",
		"link": "https://github.com/Godiesc/opera-gx",
		"description": "Firefox Theme CSS to Opera-GX Lovers.",
		"image": "https://user-images.githubusercontent.com/22057609/146305253-e257fbc0-993b-4e79-a0b4-0c0e6c95228b.png",
		"tags": [ "Godiesc", "dark", ... ]
}

}
```

**Comment by Godiesc** [comment]
I edited my before comment, or I should write other?

**Comment by BeyondMagic** [comment]
It's fine, thanks for the addition!

**Comment by Anoms12** [comment]
@Godiesc I would like to introduce you to **Sine**, the external mod manager designed for Firefox-based browsers! It offers extensive support for all your Firefox modifications, including `userChrome.css`, `userContent.css`, and user-scripts.

Getting started is simple:

* Add a `theme.json` file to your repository (check out this [reference](https://github.com/Anoms12/Advanced-Tab-Groups/blob/main/theme.json)).

* Then, publish your mod to Sine using [this issue template](https://github.com/CosmoCreeper/Sine/issues/new?template=add-theme.yml).

* If your mod includes configurable options, you can create a `preferences.json` file by [following this wiki](https://github.com/CosmoCreeper/Sine/wiki/Preferences).

The maintainer is very responsive and will review your submission quickly.

Have questions or need assistance? Feel free to tag me!

_Note: Sine currently works with Zen Browser, but version 2, bringing support to all Firefox-based browsers, is just around the corner! Expect the dev branch (Cosine) to be updated with it tonight._
