### ISSUE TITLE
[NEWTHEME] Firefox Safari 15 Theme

### ISSUE THREAD

**Issue by denizjcan** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#166]
```
{
		"title": "Firefox 'Safari 15' Theme",
		"link": "https://github.com/denizjcan/Firefox-Safari-15-Theme",
		"description": "A Firefox theme that emulates the Safari 15 interface and new tab page",
		"image": "https://github.com/denizjcan/Firefox-Safari-15-Theme/blob/main/Resources/safari2.png?raw=true"
	}
```

**Comment by Neikon** [comment]
`{
		"title": "Firefox 'Safari 15' Theme",
		"link": "https://github.com/denizjcan/Firefox-Safari-15-Theme",
		"description": "A Firefox theme that emulates the Safari 15 interface and new tab page",
		"image": "https://github.com/denizjcan/Firefox-Safari-15-Theme/blob/main/Resources/safari2.png?raw=true"
               "tags": [ "clean", "compact", "aestheticfox", "minimal", "minimalistic", "aesthetic"]
	}`
	Please add some tags. I have put some random tags as an example

**Comment by denizjcan** [comment]
Thank you

		"title": "Firefox 'Safari 15' Theme",
		"link": "https://github.com/denizjcan/Firefox-Safari-15-Theme",
		"description": "A Firefox theme that emulates the Safari 15 interface and new tab page",
		"image": "https://raw.githubusercontent.com/denizjcan/Firefox-Safari-15-Theme/main/Resources/safari3.png"
		"tags": [ "clean", "compact", "oneline", "safari", "ventura", "aesthetic", "mac"]
