### ISSUE TITLE
Please consider removing silentfox as it is no longer alive

### ISSUE THREAD

**Issue by coderx546** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#169]
![image](https://user-images.githubusercontent.com/96462198/219899117-b2940bf2-4fbd-4959-a4a7-877dad8746cc.png)
I was the owner of silentfox but didn't have to resources to maintain it so I deleted the repo. Now its just there with a non functioning link.

**Comment by Neikon** [comment]
thanks for the warning I will remove it now
