### ISSUE TITLE
Security Risk – insertAdjacentHTML

### ISSUE THREAD

**Issue by andreasgrafen** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#17]
While I really like the use of template literals, using `insertAdjacentHTML` in our [main.js](https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/blob/be0f32c696923c8d76d8a242dddde17dfaf57f45/dev/js/main.js#L22) has one major flaw: We need to make sure that we sanatise the JSON data.

As long as we manually review and merge new themes this isn't a big deal.  But if we decide to fully automate the process later on we have to keep that in mind to prevent unwanted JavaScript from getting invoked at runtime.

**Comment by BeyondMagic** [comment]
I don't see we automating this process later or sooner, the images of the themes must be revised and, while, we can, somehow make the rest of structure of the theme automatized, the image still something that we need to go on and look one by one.

Now, I agree with you that `insertAdjacentHTML` is not fully secure as the way it is right now, and, cleaning each property before passing it to the DOM will resolve it, I assume.

**Comment by andreasgrafen** [comment]
Yeah, no worries. I just chose the complicated way to avoid any kind of XSS. Template literals are hell of a lot cleaner and easier to maintain tho. It's a good edit for sure. c:

**Comment by BeyondMagic** [comment]
Verify caf2e25.

**Comment by andreasgrafen** [comment]
Nice changes!

I've also tinkered around a little with the escaping of out input. I've found a rather simple (and maybe obscure) way to make sure that whatever is stored inside our JSON is only displayed as text on runtime.
Feel free to check the [alt.js](https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/blob/frontend/dev/js/alt.js) file. This is only the sanatising/rendering part – ofc the rest of your changes would need to get implemented as well. I just wanted to share this for further review first. ^—^

**Comment by BeyondMagic** [comment]
Way better than the code I wrote, you did magic there, lol.

And I am not familiar with Github actions, unfortunately, too. But looking at the [github checks](https://docs.github.com/en/rest/reference/checks), it seems a little bit *limited*?

**Comment by andreasgrafen** [comment]
Don't be so harsh on yourself. I basically took your code and just put it in a fancy class. :D

GitHub checks indeed seems a little limited, but I think Actions allows for simple shell-like scripts. From what I can gather It should be possible to write a shallow check on that.
