### ISSUE TITLE
Add multiple themes 

### ISSUE THREAD

**Issue by Zabooby** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#175]
I'm not sure if you accept requests to add themes from people that don't maintain them. But if you do here are two I think should be added. 

https://github.com/rafaelmardojai/firefox-gnome-theme
https://github.com/BloodyHell619/Firefox-Theme-DarkMatter

**Comment by Neikon** [comment]
I have asked them via an issue in their repositories, we will see in the next days what they answer.

https://github.com/rafaelmardojai/firefox-gnome-theme/issues/586
https://github.com/BloodyHell619/Firefox-Theme-DarkMatter/issues/1

**Comment by Zabooby** [comment]
Should I close this issue as you've opened issues the repos?

**Comment by Neikon** [comment]
> Should I close this issue as you've opened issues the repos?

let's keep it open to remind us to check the issues in the original repo.
