### ISSUE TITLE
[NEWTHEME] Essence

### ISSUE THREAD

**Issue by JarnotMaciej** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#185]
```
{
		"title": "Essence",
		"link": "https://github.com/JarnotMaciej/Essence",
		"description": "Compact, beautiful and minimalistic theme for the Firefox web browser.",
		"image": "https://github.com/JarnotMaciej/Essence/assets/92025751/de5ec935-e021-46b6-8e50-fee27d95e6dc"
                "tags": [ "compact", "minimal", "light", "modern", "oneline", "rounded", "clean" ]
}
```

**Comment by Anoms12** [comment]
@JarnotMaciej I would like to introduce you to **Sine**, the external mod manager designed for Firefox-based browsers! It offers extensive support for all your Firefox modifications, including `userChrome.css`, `userContent.css`, and user-scripts.

Getting started is simple:

* Add a `theme.json` file to your repository (check out this [reference](https://github.com/Anoms12/Advanced-Tab-Groups/blob/main/theme.json)).

* Then, publish your mod to Sine using [this issue template](https://github.com/CosmoCreeper/Sine/issues/new?template=add-theme.yml).

* If your mod includes configurable options, you can create a `preferences.json` file by [following this wiki](https://github.com/CosmoCreeper/Sine/wiki/Preferences).

The maintainer is very responsive and will review your submission quickly.

Have questions or need assistance? Feel free to tag me!

_Note: Sine currently works with Zen Browser, but version 2, bringing support to all Firefox-based browsers, is just around the corner! Expect the dev branch (Cosine) to be updated with it tonight._
