### ISSUE TITLE
Use /docs folder for deployment

### ISSUE THREAD

**Issue by andreasgrafen** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#19]
GitHub Pages offers to serve from the `/docs` folder instead of the root directory.
I'd suggest that we switch to that to declutter the repository a little bit.

What are your thoughts on this? c:

**Comment by BeyondMagic** [comment]
Yeah, I think we can change it to docs, but, I don't see we using it a lot, it is quite a simple project right now, but maybe we can handle common bugs of themes, FAQ and those type of things there.

**Comment by andreasgrafen** [comment]
Oh, no. I might have explained this poorly.

Currently the frontend serves right from the main directory (/root) but GitHub Pages allows users to alternatively serve from a subfolder (/docs). More common names would be public or dist, I think.
This way we wouldn't have the assets folder, robots.txt, index.html and all that in the main directory but rather in a subfolder. I think that would make everything look and feel a little bit more organised.

**Comment by BeyondMagic** [comment]
Ah, 😓. Yes, let's do that, it's better than putting all those files in the root, also, we have a file called README.txt, I think we can delete it since the project is not using the Multiverse HTML5 template anymore.

But about the wiki, we can consider adding one if we need a FAQ.

**Comment by andreasgrafen** [comment]
Yeah, that sounds like a plan! Let's hear what @Neikon thinks about this. c:

I'd suggest that we wait for the current pull requests to be resolved and then just change the gulp config real quick to automatically build into the `/docs` folder. I'd offer myself to clean up the repo then as well. :D

**Comment by Neikon** [comment]
of course, yes. but as you say, let's first resolve the pull requests we have open.

**Comment by andreasgrafen** [comment]
Since everything seems to be rresolved forr now I went ahead and changed the build folder.
Gulp now automatically builds into `/docs` and everything is served from there. ^—^

**Comment by andreasgrafen** [comment]
Update: Appaently GitHub doesn't allow for anything outside the `/docs` folder to ba addressed.
I've just copied the `themes.json` over for now to fix this. Another way would be to hard link the URL but I dislike the idea. IÄll take a look at a possible fix later.

**Comment by andreasgrafen** [comment]
It's fixed now. I've added a task to the gulp file in order to copy over the themes.json from `/` into `/docs` when the project is built. Since this prevents from changes being deployed immediately on change this also acts as another safety switch in case anything is wrong with the themes file.
