### ISSUE TITLE
[NEWTHEME] Firefox-Alpha 🗿

### ISSUE THREAD

**Issue by Tagggar** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#192]
```
{
		"title": "Firefox-Alpha",
		"link": "https://github.com/Tagggar/Firefox-Alpha",
		"description": "Super clear desktop browser with zero buttons and gesture controls",
		"image": "https://raw.githubusercontent.com/Tagggar/Firefox-Alpha/main/assets/preview.gif"
}
```

**Comment by Neikon** [comment]
Give us some at least 4 tags pls. 
here some examples "tags": ["oneline", "responsive", "light", "dark", "animation", "rounded", "compact", "minimalistic", "black"]

**Comment by Neikon** [comment]
thanks to you for sharing your topic

**Comment by Tagggar** [comment]
The theme image is blank.

It looks like the site is trying to load:

`assets/img/themes  //  23823preview.webp`

instead of `...  /  23823preview.gif`

Please, help!

**Comment by Neikon** [comment]
fixed now.

**Comment by Tagggar** [comment]
Thanks Boss

**Comment by Anoms12** [comment]
@Tagggar I would like to introduce you to **Sine**, the external mod manager designed for Firefox-based browsers! It offers extensive support for all your Firefox modifications, including `userChrome.css`, `userContent.css`, and user-scripts.

Getting started is simple:

* Add a `theme.json` file to your repository (check out this [reference](https://github.com/Anoms12/Advanced-Tab-Groups/blob/main/theme.json)).

* Then, publish your mod to Sine using [this issue template](https://github.com/CosmoCreeper/Sine/issues/new?template=add-theme.yml).

* If your mod includes configurable options, you can create a `preferences.json` file by [following this wiki](https://github.com/CosmoCreeper/Sine/wiki/Preferences).

The maintainer is very responsive and will review your submission quickly.

Have questions or need assistance? Feel free to tag me!

_Note: Sine currently works with Zen Browser, but version 2, bringing support to all Firefox-based browsers, is just around the corner! Expect the dev branch (Cosine) to be updated with it tonight._
