### ISSUE TITLE
Removing the WaveFox theme from the repository

### ISSUE THREAD

**Issue by QNetITQ** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#193]
Please remove the theme from the theme repository

**Comment by Neikon** [comment]
Of course. 
If it is not too much trouble, can I ask for the reason?

**Comment by QNetITQ** [comment]
Initially, this repository assumed equal access to styles for the browser, implied competition between style authors and, as a result, improved quality, and it worked. However, under current conditions, it can no longer perform this function. There are several Firefox forks that already contain 1 or 2 styles and promote them and are not neutral. Their styles cover most of the user's needs and even automatically update with the browser. No one will go into the repository and look for what they need from more than 50 styles, half of which have long been abandoned and will have to be updated manually every month. Human laziness served a disservice here, as always. Competition between authors is also not possible due to forks and their built-in styles. It's a shame, but a good idea was simply buried out of nowhere.

**Comment by Neikon** [comment]
Thank you for sharing your reasons. As for this repository, I would love to be able to validate the functionality of each theme, but I can't do it alone. In the end, I'm waiting for someone to find a bug and report it as an issue. Thank you very much for sharing your theme and I hope you can come back someday.
