### ISSUE TITLE
[NEWTHEME] Dark Star

### ISSUE THREAD

**Issue by ivelieu** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#197]
```
{
		"title": "Dark Star",
		"link": "https://gitlab.com/ivelieu/dark-star-firefox-skin",
		"description": "A color-customizable, zero navbar padding skin, modified from Starry Fox",
		"image": "https://gitlab.com/ivelieu/dark-star-firefox-skin/-/raw/main/showcase/darkstar_3.png"
                "tags": [ "Ivelieu", "dark", "minimal", "zeropadding", "customizable"]
}
```

**Comment by Anoms12** [comment]
@ivelieu I would like to introduce you to **Sine**, the external mod manager designed for Firefox-based browsers! It offers extensive support for all your Firefox modifications, including `userChrome.css`, `userContent.css`, and user-scripts.

Getting started is simple:

* Add a `theme.json` file to your repository (check out this [reference](https://github.com/Anoms12/Advanced-Tab-Groups/blob/main/theme.json)).

* Then, publish your mod to Sine using [this issue template](https://github.com/CosmoCreeper/Sine/issues/new?template=add-theme.yml).

* If your mod includes configurable options, you can create a `preferences.json` file by [following this wiki](https://github.com/CosmoCreeper/Sine/wiki/Preferences).

The maintainer is very responsive and will review your submission quickly.

Have questions or need assistance? Feel free to tag me!

_Note: Sine currently works with Zen Browser, but version 2, bringing support to all Firefox-based browsers, is just around the corner! Expect the dev branch (Cosine) to be updated with it tonight._
