### ISSUE TITLE
Fixes that will bring the ability to support NixOS home-manager

### ISSUE THREAD

**Issue by LennyLizowzskiy** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#200]
**Is your feature request related to a problem? Please describe.**
I want to create a [NixOS](https://nixos.org/) flake that will contain all the themes from `themes.json`. For that, I need a 100% stable way to get all the CSS that need to be imported and all the Firefox settings that should be changed in order to use the theme.

**Describe the solution you'd like**
Add those descriptors to the `themes.json` file so they can be easily parsed so then I can create a home-manager module and make a PR to `home-manager` repo and/or to this repository in form of `flake.nix` (many github repos already include a way to easily use them on NixOS, ex. Hyprland (Wayland window manager) - https://github.com/hyprwm/Hyprland/blob/main/flake.nix)

**Additional context**
We can already easily [configure Firefox declaratively on NixOS](https://mipmip.github.io/home-manager-option-search/?query=programs.firefox).
![image](https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/assets/46971551/80ad4e5c-3635-4e50-ac27-6d1f03b7dcf8)
So I can write a module that will provide NixOS users with something like:
```nix
programs.firefox.profiles.<name>.cssStoreTheming = {
  enable = true;
  theme = pkgs.firefoxCssStore.themes.essense;
}
```

**Comment by Neikon** [comment]
I think it's a great idea, but it depends more on the author of the theme himself than on us in the end. Since we just link to the original repo.

I propose you to add a key to the json to indicate if the theme repo supports the methodology you need and that you invite the authors to adopt it. 

Also, we can add a section to the web where you can explain to the author how to adapt his repo and to the user how to use Nixos to install the themes.

What do you think?

**Comment by LennyLizowzskiy** [comment]
> I think it's a great idea, but it depends more on the author of the theme himself than on us in the end. Since we just link to the original repo.
> 
> I propose you to add a key to the json to indicate if the theme repo supports the methodology you need and that you invite the authors to adopt it. 
> 
> Also, we can add a section to the web where you can explain to the author how to adapt his repo and to the user how to use Nixos to install the themes.
> 
> What do you think?

I think I can edit the existing `themes.json` myself because that's not that big of a deal really. Also I can add info about the new setup in the README as well. I think I will do that in 2 separate PRs then

**Comment by LennyLizowzskiy** [comment]
@Neikon here's the schema that I came up with. Should anything be added or changed?

```jsonc
/***** Old*****/
{
    "title": "u/FffDtark's Theme",
    "link": "https://github.com/Ikrom27/Firefox",
    "description": "Oneline theme",
    "image": "assets/img/themes/My_Firefox_theme_-_uFffDtark.webp",
    "tags": [ "dark", "Ikrom27", "centre", "one-line" ]
}

/***** New *****/
{
    "title": "Dark Star",
    "description": "A color-customizable, zero navbar padding skin, modified from Starry Fox"
    "tags": [ "Ivelieu", "dark", "minimal", "zeropadding", "customizable" ],
    "images": [
        "assets/img/themes/11608darkstar_3.webp" // here it references the FirefoxCSS-Store repo path
    ],
    "links": {
        "homepage": "https://gitlab.com/ivelieu/dark-star-firefox-skin",
        "source": "https://gitlab.com/ivelieu/dark-star-firefox-skin/-/archive/main/dark-star-firefox-skin-main.zip"
    },
    "install": { // every path here references the unpacked [links.source] path
        /*  Nullable
            Use the dot symbol to use the downloaded file as src
            Example:
                [links.source] points to "https://gitlab.com/ivelieu/dark-star-firefox-skin/-/raw/main/chrome/userChrome.css?ref_type=heads&inline=false"
                So you should use the "." here to point that the downloaded file must be used as "userChromeSrc" */
        "userChromeSrc": "chrome/userChrome.css",
        "userContentSrc": "chrome/userContent.css", // Same as above
        "additionalFiles": [ // Required files for the theme (ex. icons), same schema as before, can be directories or files themselves
            "chrome/fox_lightpink.png",
            "chrome/images",
            "chrome/resources"
        ], // Nix script will see that "chrome" as a base directory and use it as base (because CSS files only use current directory and dirs that are included there)
        "firefoxConfigChanges": [
            "browser.display.background_color.dark" = "#000000",
            "browser.display.use_system_colors" = false
        ],
        "messageAfterSetup": "hey, you can read https://github.com/sagars007/starry-fox#readme for some tips!", // maybe we need to tell user to install some extensions to make their UX/UI better
    }
}
```

**Comment by LennyLizowzskiy** [comment]
I think we can add a link to author as separate entry in the `links`

**Comment by Neikon** [comment]
This scheme would be fine if all authors had the repos in the same form, but many do not have either releases or .zip files. So I was thinking of something simpler in our part of the theme.json.

```js
// theme.json in this repo
{
    "title": "Dark Star",
    "description": "A color-customizable, zero navbar padding skin, modified from Starry Fox"
    "tags": [ "Ivelieu", "dark", "minimal", "zeropadding", "customizable" ],
    "images": [
        "assets/img/themes/11608darkstar_3.webp" // here it references the FirefoxCSS-Store repo path
    ],
   "nixos_theme_support": True  // maybe can be named "self-installable" or whatever
    "links": {
        "homepage": "https://gitlab.com/ivelieu/dark-star-firefox-skin",
        "nixos": ""https://gitlab.com/ivelieu/dark-star-firefox-skin/nixos_sheme.json" // Empty if nixos_theme == False
    },
}
```

```js
// nixos_sheme.json in the author repo 
// ( This is a quick sketch and it may be terribly wrong because I just copied the install part.)
"install": { // every path here references the unpacked [links.source] path
        "messageAfterSetup": "hey, you can read https://github.com/sagars007/starry-fox#readme for some tips!", // maybe we need to tell user to install some extensions to make their UX/UI better
        /*  Nullable
            Use the dot symbol to use the downloaded file as src
            Example:
                [links.source] points to "https://gitlab.com/ivelieu/dark-star-firefox-skin/-/raw/main/chrome/userChrome.css?ref_type=heads&inline=false"
                So you should use the "." here to point that the downloaded file must be used as "userChromeSrc" */
        "userChromeSrc": "chrome/userChrome.css",
        "userContentSrc": "chrome/userContent.css", // Same description as above
        "additionalFiles": [ // Required files for the theme (ex. icons), same schema as before, can be directories or files themselves
            "chrome/fox_lightpink.png",
            "chrome/images",
            "chrome/resources"
        ], // Nix script will see that "chrome" is a base directory for the userChrome and will use it as base (because CSS files only use current directory and dirs that are included there)
        "firefoxConfigChanges": [
            "browser.display.background_color.dark" = "#000000",
            "browser.display.use_system_colors" = false
        ]
    }
```

This will make sure that you know if a theme supports your needs for nixos. Avoiding errors and delegating support to the author's repo and not ours.

Additionally, if the author does not support, but you or someone else wants to support X theme. We can link the nixos_sheme.json in our own repo but with a warning.
The nixos support for this theme is not offered by the author, so it might fail.

What do you think this would work?

**Comment by LennyLizowzskiy** [comment]
@Neikon 

> This scheme would be fine if all authors had the repos in the same form, but many do not have either releases or .zip files

We are downloading their repo master branch _OR_ one CSS file (userChrome or userContent). Not the release package of git repository or some random zip file. So that makes things a lot easier.

> "nixos_theme_support": True  // maybe can be named "self-installable" or whatever

Yeah, my intention is to be also able easily create `.bat` and `.sh` scripts for quick install from the main repo. It's quite easy to do as far as I can tell.

> This will make sure that you know if a theme supports your needs for nixos

But every theme **must** include at least one CSS file. Usually it's CSS file and some icons. And my JSON-schema fully supports it. 

> Additionally, if the author does not support, but you or someone else wants to support X theme

Ok, no author link then. Didn't think about that

> The nixos support for this theme is not offered by the author, so it might fail.

It will not fail because it modifies settings in the exact same way as you would normally do manually. In short, Nix home-manager just creates some files on its own and links them into the `$HOME/.config` directory. It's just that you do that declaratively like configuring any GitHub action but instead of YAML file there's nixlang with function support (you can think of nixlang as "JSON with functions")

**Comment by LennyLizowzskiy** [comment]
I think we can add a feature for "targeted copying". Like linking folders in Docker.
So the idea is:

// Now
"additionalFiles": [
    "chrome/fox_lightpink.png",
    "chrome/images",
    "chrome/resources"
]

Optional feature:
"additionalFiles": [
    "chrome/fox_lightpink.png:^", // ^ for the original file name, so it copies inside the root of the Firefox profile
    "chrome/images",
    "chrome/resources"
]
So in the first entry we will make a copy of a file chrome/fox_lightpink.png to the `

**Comment by LennyLizowzskiy** [comment]
Now that I think of it, there's a major flaw in case of Nix. It requires you to lock the version by adding the sha256 of the downloaded archive. So this design will allow other Linux, macOS and Windows users to create a shell script or a `bat` file, but not the home-manager users do the thing. I completely forgot about that, lol

**Comment by LennyLizowzskiy** [comment]
I think that it will require from me a completely different approach then and the approach that I think of cannot be integrated with this repository because I will need to package each theme as its own separate package manually in my own nix-user-repository

**Comment by LennyLizowzskiy** [comment]
Closing this as I will start to do the described thing in the other repo
