### ISSUE TITLE
[NEWTHEME] ArcWTF

### ISSUE THREAD

**Issue by KiKaraage** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#225]
```
{
		"title": "ArcWTF",
		"link": "https://github.com/KiKaraage/ArcWTF/",
		"description": "UserChrome.css theme to bring Arc Browser look from Windows to Firefox! ",
		"image": "https://private-user-images.githubusercontent.com/10529881/301477254-0f3711c7-4841-464f-b5d0-8b78bd4e0402.png"
                "tags": [ "KiKaraage", "dark", "light", "Arc Browser", "Sidebery", "vertical tabs", "autohide", "minimal" ]
}
```

**Comment by Neikon** [comment]
the img doesn't load, it's a public url?

**Comment by KiKaraage** [comment]
> the img doesn't load, it's a public url?

That's a image URL i grabbed from my README.md. Should I reupload it again?

**Comment by BeyondMagic** [comment]
@KiKaraage 

Use the image link from the your repository files: https://github.com/KiKaraage/ArcWTF/assets/10529881/0f3711c7-4841-464f-b5d0-8b78bd4e0402; not the image link it is rendered from the README.md.
