### ISSUE TITLE
Cannot find Minimal-Arc both by scrolling and search on website

### ISSUE THREAD

**Issue by zayihu** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#258]
**Describe the bug**
Hello! Sorry for bothering you, but my pull request https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/pull/256 was merged and applied to main branch, and site redeployed, but I can't find my theme on https://firefoxcss-store.github.io/

**To Reproduce**
1. Go to 'https://firefoxcss-store.github.io/'
3. Scroll down to end, I find no Minimal-Arc
4. Search Minimal-Arc, find nothing

**Expected behavior**
Being able to find Minimal-Arc theme both by scrolling and search

**Screenshots**
![Screenshot_20240607_100430](https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/assets/167391787/d114f894-f864-4f45-82ec-d31b02e08d67)

**Comment by BeyondMagic** [comment]
Fixed. Thanks for warning me!

However, as you may seem, the image is not correctly encoded, this has passed through our eyes unnoticed, so I ask to contribute once more by sharing an image for the cover of it.

**Comment by zayihu** [comment]
Thank you! Weird, encoded by GIMP, viewable without any problems or errors in both browser and image viewers.

**Comment by zayihu** [comment]
Something is weird with deployment, image changed in recent commit -> https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/commit/d52581b732714598385be10739210913d9fe912d, but after redeploy nothing changes on site.
Tried on all browsers or Private mode. Same. Maybe reopen this issue? Thank you!
![Screenshot_20240607_134904](https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/assets/167391787/0353bd79-c804-4e5d-bc73-d0b08f66b502)
