### ISSUE TITLE
Disclaimer Changes Proposal

### ISSUE THREAD

**Issue by andreasgrafen** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#26]
The more I think about it, the more I want to change _the company_ to something different. It just doesn't really sound all that fitting. Maybe something like _the author_ would be better?

**Comment by BeyondMagic** [comment]
Or maybe just change `FirefoxCSS Store` to `FirefoxCSS Store Developers`.
![image](https://user-images.githubusercontent.com/51831435/106969007-cbc57400-6728-11eb-96ed-23fb409bc1cb.png)

**Comment by andreasgrafen** [comment]
Yeah, that's also a good idea. I like that!
But I still just really dislike the sound of »company«… it's so corporate. D:

**Comment by BeyondMagic** [comment]
I agree with you on that, it's better another word, but why `author`?

**Comment by andreasgrafen** [comment]
I don't know. While it sounds a lot better than company I don't think that author is really the best word to use. Right now nothing else somes to mind tho.

**Comment by BeyondMagic** [comment]
I mean, it's singular, a plural noun would be better, wouldn't?

**Comment by andreasgrafen** [comment]
Yeah, but I've seen it being used to refer to a group in the past in similar context.
Maybe just **team**/**the team** would work? That pretty straight to the point, isn't it?

**Comment by BeyondMagic** [comment]
Yeah, team or, *I don't know*, crew, works great.

**Comment by andreasgrafen** [comment]
The Crew™ courtesy of Ubisoft. :^)
I like that. Crew or team sounds nice and fitting.

**Comment by andreasgrafen** [comment]
What are your thought on this, @Neikon? c:

**Comment by Neikon** [comment]
> 
> 
> What are your thought on this, @Neikon? c:

I am in favor of changing it so as not to look like a big corporation. But I can't help to find a substitute, I lack the level of English to know nuances and connotations. In fact I write this text with the help of a translator because I had no idea how to write "matices/nuances" and "connotaciones/connotations" in English XD. Yes, the second one is very similar 😅I know that now U.U

but if we don't find a word that fits I'm not too worried about it either. It is a technical-legal text that uses the word "company" as a generic word and explains it in the definitions section.

**Comment by sheeepdev** [comment]
maybe, this project?

**Comment by LongJohn-Silver** [comment]
Not that my opinion matters, but IMO "Team" sound formal and not corporate, whereas "Crew" sounds a bit too informal.

**Comment by Neikon** [comment]
> 
> 
> Not that my opinion matters, but IMO "Team" sound formal and not corporate, whereas "Crew" sounds a bit too informal.

all opinions are welcome thanks, in fact I forgot about this, I will try to change it next week. Unless someone kindly goes ahead of me and changes the word "company" to "team" which seems to be the one I like the most.

**Comment by andreasgrafen** [comment]
Done! c:
I've forgot to change the date tho, but since it's only a word that has changed I think it's fine.
