### ISSUE TITLE
Not a valid JSON

### ISSUE THREAD

**Issue by Loskir** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#261]
After this commit https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/commit/ae4f8d8b3530c646e172ce2b8ac68548a0e2c951 themes.json is not a valid JSON because of trailing comma and the website does not load properly
<img width="536" alt="image" src="https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/assets/21295738/f1b9632f-9696-4a6a-ba63-73c8fa2159ee">

**Comment by BeyondMagic** [comment]
Thanks! I really did not see that, my bad!
