### ISSUE TITLE
[NEWTHEME] Minimal Gruvbox Material Firefox

### ISSUE THREAD

**Issue by RemyIsCool** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#263]
```
{
		"title": "Minimal Gruvbox Material Firefox",
		"link": "https://github.com/RemyIsCool/userChrome.css",
		"description": "A minimal Firefox/LibreWolf theme with satisfying animations and Gruvbox Material colors.",
		"image": "https://raw.githubusercontent.com/RemyIsCool/userChrome.css/main/preview.gif"
                "tags": ["RemyIsCool", "dark", "minimal", "gruvbox material", "animations"]
}
```

**Comment by BeyondMagic** [comment]
Thank you for your contribution! It seems Github is currently a little slow redeploying last changes, but it has been added to the list!

**Comment by Anoms12** [comment]
@RemyIsCool I would like to introduce you to **Sine**, the external mod manager designed for Firefox-based browsers! It offers extensive support for all your Firefox modifications, including `userChrome.css`, `userContent.css`, and user-scripts.

Getting started is simple:

* Add a `theme.json` file to your repository (check out this [reference](https://github.com/Anoms12/Advanced-Tab-Groups/blob/main/theme.json)).

* Then, publish your mod to Sine using [this issue template](https://github.com/CosmoCreeper/Sine/issues/new?template=add-theme.yml).

* If your mod includes configurable options, you can create a `preferences.json` file by [following this wiki](https://github.com/CosmoCreeper/Sine/wiki/Preferences).

The maintainer is very responsive and will review your submission quickly.

Have questions or need assistance? Feel free to tag me!

_Note: Sine currently works with Zen Browser, but version 2, bringing support to all Firefox-based browsers, is just around the corner! Expect the dev branch (Cosine) to be updated with it tonight._
