### ISSUE TITLE
Site content as MD

### ISSUE THREAD

**Issue by andreasgrafen** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#27]
I've created a [feature branch](https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/tree/markdown-support) for markdown in Pug support. This way site content (like the disclaimer) would also get displayed nicely when viewed on GitHub – well, and it's easier to write for people that aren't used to pug.

I really like the idea and it doesn't really add any extra bloat. This could come in quite handy when we decide that we maybe want to display more content on the site. Things that I have in mind would be the generic tutorial or the theme submission guideline. c:

What are your thoughts on this?

**Comment by BeyondMagic** [comment]
`great++;`
