### ISSUE TITLE
[Build actions] Fail, img-switch.sh not found

### ISSUE THREAD

**Issue by Neikon** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#293]
It fails because it can't find the script, but it was removed because it wasn't needed.  It was deleted in this commit 553ecf5f0a38ba240fde4e34ba074fce718be484  

We should take the opportunity to put the automatic build when a pull request is merged.

@BeyondMagic Could you take a look at it when you have time please?

**Comment by BeyondMagic** [comment]
Yeap, fixed with 53066ff1a939d01cef0a0418444b1a06d08e4cc0.
