### ISSUE TITLE
Sort randomly

### ISSUE THREAD

**Issue by Neikon** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#30]
they could be sorted randomly on the user's device or every time we add a new theme.
Can we do that?

**Comment by BeyondMagic** [comment]
Yes, but why? I think sorting it as the most recent themes or the oldest ones is better.

**Comment by Neikon** [comment]
That would give all the themes the same chance to be seen or to appear in the first ones. But I also think it's a good idea to organize them by the most recent ones. 

I think that ideally when the user loads the site they should appear in random order and change each time the user re-enters and also have a button to organize them by most recent.

But really I'll be happy with either way

**Comment by BeyondMagic** [comment]
The button can work out, it's better, but as default I still think that recent ones can do that.

**Comment by andreasgrafen** [comment]
mmh, that's a tough one! Right now I think it's displaying on order form oldest entry to the newest? Turning that around is quite easy and can be done just by changing the order in `themes.json`. The random orrder should be doable with JS, I think?
Let me throw another dumb idea into the room: We could query the GitHub API to sort by the amount of stars the themes Repo has … :D

**Comment by Neikon** [comment]
> 
> 
>  We could query the GitHub API to sort by the amount of stars the themes Repo has … :D

that would be nice, 

I will sort by date tomorrow (newest first)

**Comment by BeyondMagic** [comment]
> The random orrder should be doable with JS, I think?

Yeah, that's not hard at all, nor the newest ones and the oldest ones.

> We could query the GitHub API to sort by the amount of stars the themes Repo has … :D

Yep, perfect.
