### ISSUE TITLE
Add FirefoxW10ContextMenus

### ISSUE THREAD

**Issue by M1ch431** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#33]
I hesitated to submit this since it's not a complete theme, but I feel like it's worthy to display in a CSS Store.

https://github.com/M1ch431/FirefoxW10ContextMenus

```
{
		"title": "FirefoxW10ContextMenus",
		"link": "https://github.com/M1ch431/FirefoxW10ContextMenus",
		"description": "Emulates the Windows 10 context menus in Firefox.",
		"image": "https://raw.githubusercontent.com/M1ch431/FirefoxW10ContextMenus/master/Preview.png"
}
```

**Comment by BeyondMagic** [comment]
It seems very good, we can highlight this item somehow in the display of themes since it's quite different from the other ones. :)

**Comment by BeyondMagic** [comment]
It seems very good, I didn't even know Firefox had "secret options", it uses **chromeUser.css**, so, it stills a theme and there's no problem adding it. Thanks for your contribution.
