### ISSUE TITLE
Download options not showing up in smaller screens

### ISSUE THREAD

**Issue by BeyondMagic** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#6]
In a screen of 798x744 there's no options to download, nor preview. Going to give a look and update here.

![image](https://user-images.githubusercontent.com/51831435/105860962-f139db80-5fcc-11eb-886c-9d6be891fcfe.png)

**Comment by andreasgrafen** [comment]
This would get fixed automatically with the current state of the [autoload-js branch](https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/tree/autoload-js) as explained in [this comment](https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/issues/2#issuecomment-767463329). I personally think that the lightbox is overkill anyway. :shrug:

**Comment by BeyondMagic** [comment]
All right, just as a temporary fix I'll pull request in the main branch for now.
