### ISSUE TITLE
Add last updated date to themes

### ISSUE THREAD

**Issue by LongJohn-Silver** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#68]
**Is your feature request related to a problem? Please describe.**

Not having this information readily available, and having to go to all theme's repository to know this.

**Describe the solution you'd like**

I think having a last updated date somewhere would be useful to let people know if they want to use it, because otherwise maybe the theme will be outdated or will not work properly.

Additionally, maybe having something like "Photon compatible", "Proton compatible, and so on, since there some forks of Firefox that are not up to date in comparison or use other themes may be compatible with older versions.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Neikon** [comment]
Thanks for the feedback

Right now they are ordered from newest to oldest but you are right that this does not include updates. Our intention is that all linked themes are compatible with the stable version of firefox. 

But in this transition stage we could add that info in the theme description so you can see it with a mouse over. Something like "Compatible with: 89+"

If someone wants to do it or has another idea go ahead and send a pull request with those changes if not I'll implement it next week.

**Comment by LongJohn-Silver** [comment]
> Thanks for the feedback

You're welcome!

> Right now they are ordered from newest to oldest but you are right that this does not include updates. Our intention is that all linked themes are compatible with the stable version of firefox.
> 
> But in this transition stage we could add that info in the theme description so you can see it with a mouse over. Something like "Compatible with: 89+"

Sounds nice, but still I think that sooner or later some of those will have some issues (or not) with Firefox if they are not kept up to date within the monthly Firefox updates, so it's good to know how outdated it is, so at least one can know and go ahead and try it out anyways to see if it works. This is, of course, unless a requirement to be listed is that they are always compatible with latest Release version, this does not mean that it needs to be updated monthly, just that they make sure it works.

> If someone wants to do it or has another idea go ahead and send a pull request with those changes if not I'll implement it next week.

Unfortunately I don't have the knowledge to do this myself, maybe if it was just adding some HTML and text I would be able to do it but I'm no good with CSS.

**Comment by Neikon** [comment]
On the website there should only be themes compatible with the current stable version of firefox, however I have added compatibility information to the description. Themes that are not compatible or are not supported by their creators will be moved to another section of the website. It would be great if, if a user discovers a serious problem with a theme or if a theme has been abandoned, he/she could create an issue and warn us about it.
![imagen](https://user-images.githubusercontent.com/1765319/121503782-ad76ca00-c9e1-11eb-8f17-8cf595c6d6ef.png)
