### ISSUE TITLE
Thunderbird section

### ISSUE THREAD

**Issue by ScanuNicco** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#97]
Mozilla Thunderbird also supports customization through the `userchrome.css` file. It would be very useful if the store had a separate section for Thunderbird.

**Comment by Neikon** [comment]
Give us more information pls, a link to a community where topics are shared or something. I am totally unfamiliar with the subject.

**Comment by ScanuNicco** [comment]
Thunderbird customizations tend to be useful tweaks rather than the complete redesigns that you see for Firefox. Thunderbird doesn't have a dedicated subreddit for userchrome.css, or really any central place where you can find userchrome.css themes (which is exactly why a Thunderbird section on this website would be so useful), but here's a few projects that i've found:
- https://silvercircle.github.io/software/user-chrome-thunderbird/
- https://github.com/Aris-t2/CustomCSSforTb
- https://www.reddit.com/r/Thunderbird/comments/7moybs/trying_to_make_dark_userchromecss/

There are also quite a few people on r/Thunderbird that are making userchrome.css files:
https://www.reddit.com/r/Thunderbird/search/?q=userchrome&restrict_sr=1

**Comment by Neikon** [comment]
I've asked on the thunderbird reddit to see what they have to say. https://www.reddit.com/r/Thunderbird/comments/p3l7im/do_you_think_there_is_enough_community_and_themes/?utm_source=share&utm_medium=web2x&context=3

**Comment by Neikon** [comment]
There does not seem to be enough community. There has only been one comment to my post where they said it wouldn't be worth it. 

So I am discarding this idea for the moment. It will always be possible to create a fork of this repository and create ThunderBirdCSS-Store directly if someone wants to.
